#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright © 2024-2025 Jaxydog
#
# This file is part of Cheese.
#
# Cheese is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# Cheese is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with Cheese. If not, see <https://www.gnu.org/licenses/>.
#

# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
minecraft_version = 1.21.9
yarn_mappings = 1.21.9+build.1
loader_version = 0.17.2

# Mod Properties
mod_version = 1.12.0
maven_group = dev.jaxydog
archives_base_name = cheese

# Dependencies
fabric_version = 0.134.0+1.21.9
lodestone_version = 1.8.0
